
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Adventure`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=KULTIS\SQLEXPRESS;Initial Catalog=AdventureWorks;Integrated Security=True`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace Adventure
{
    
	[Alias("Store")]
    public partial class Store : IHasId<int>    {
        [Alias("CustomerID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        public int? SalesPersonID { get; set;}
        public string Demographics { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductPhoto")]
    public partial class ProductPhoto : IHasId<int>    {
        [Alias("ProductPhotoID")]
        [AutoIncrement]
        public int Id { get; set;}
        //TODO: Handle byte format
        //public byte[]? ThumbNailPhoto { get; set;}
        public string ThumbnailPhotoFileName { get; set;}
        //public byte[]? LargePhoto { get; set;}
        public string LargePhotoFileName { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductProductPhoto")]
    public partial class ProductProductPhoto : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ProductPhotoID { get; set;}
        [Required]
        public bool Primary { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("StoreContact")]
    public partial class StoreContact : IHasId<int>    {
        [Alias("CustomerID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ContactID { get; set;}
        [Required]
        public int ContactTypeID { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Address")]
    public partial class Address : IHasId<int>    {
        [Alias("AddressID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string AddressLine1 { get; set;}
        public string AddressLine2 { get; set;}
        [Required]
        public string City { get; set;}
        [Required]
        public int StateProvinceID { get; set;}
        [Required]
        public string PostalCode { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductReview")]
    public partial class ProductReview : IHasId<int>    {
        [Alias("ProductReviewID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public string ReviewerName { get; set;}
        [Required]
        public DateTime ReviewDate { get; set;}
        [Required]
        public string EmailAddress { get; set;}
        [Required]
        public int Rating { get; set;}
        public string Comments { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("TransactionHistory")]
    public partial class TransactionHistory : IHasId<int>    {
        [Alias("TransactionID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public int ReferenceOrderID { get; set;}
        [Required]
        public int ReferenceOrderLineID { get; set;}
        [Required]
        public DateTime TransactionDate { get; set;}
        [Required]
        public string TransactionType { get; set;}
        [Required]
        public int Quantity { get; set;}
        [Required]
        public decimal ActualCost { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("AddressType")]
    public partial class AddressType : IHasId<int>    {
        [Alias("AddressTypeID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductSubcategory")]
    public partial class ProductSubcategory : IHasId<int>    {
        [Alias("ProductSubcategoryID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ProductCategoryID { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("AWBuildVersion")]
    public partial class AWBuildVersion : IHasId<byte>    {
        [Alias("SystemInformationID")]
        [AutoIncrement]
        public byte Id { get; set;}
        [Alias("Database Version")]
        [Required]
        public string Database_Version { get; set;}
        [Required]
        public DateTime VersionDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("TransactionHistoryArchive")]
    public partial class TransactionHistoryArchive : IHasId<int>    {
        [Alias("TransactionID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public int ReferenceOrderID { get; set;}
        [Required]
        public int ReferenceOrderLineID { get; set;}
        [Required]
        public DateTime TransactionDate { get; set;}
        [Required]
        public string TransactionType { get; set;}
        [Required]
        public int Quantity { get; set;}
        [Required]
        public decimal ActualCost { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductVendor")]
    public partial class ProductVendor : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int VendorID { get; set;}
        [Required]
        public int AverageLeadTime { get; set;}
        [Required]
        public decimal StandardPrice { get; set;}
        public decimal? LastReceiptCost { get; set;}
        public DateTime? LastReceiptDate { get; set;}
        [Required]
        public int MinOrderQty { get; set;}
        [Required]
        public int MaxOrderQty { get; set;}
        public int? OnOrderQty { get; set;}
        [Required]
        public string UnitMeasureCode { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("BillOfMaterials")]
    public partial class BillOfMaterial : IHasId<int>    {
        [Alias("BillOfMaterialsID")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? ProductAssemblyID { get; set;}
        [Required]
        public int ComponentID { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public string UnitMeasureCode { get; set;}
        [Required]
        public short BOMLevel { get; set;}
        [Required]
        public decimal PerAssemblyQty { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("UnitMeasure")]
    public partial class UnitMeasure : IHasId<string>    {
        [Alias("UnitMeasureCode")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Vendor")]
    public partial class Vendor : IHasId<int>    {
        [Alias("VendorID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string AccountNumber { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public byte CreditRating { get; set;}
        [Required]
        public bool PreferredVendorStatus { get; set;}
        [Required]
        public bool ActiveFlag { get; set;}
        public string PurchasingWebServiceURL { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("PurchaseOrderDetail")]
    public partial class PurchaseOrderDetail : IHasId<int>    {
        [Alias("PurchaseOrderID")]
        [Required]
        public int Id { get; set;}
        [AutoIncrement]
        public int PurchaseOrderDetailID { get; set;}
        [Required]
        public DateTime DueDate { get; set;}
        [Required]
        public short OrderQty { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public decimal LineTotal { get; set;}
        [Required]
        public decimal ReceivedQty { get; set;}
        [Required]
        public decimal RejectedQty { get; set;}
        [Required]
        public decimal StockedQty { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Contact")]
    public partial class Contact : IHasId<int>    {
        [Alias("ContactID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public bool NameStyle { get; set;}
        public string Title { get; set;}
        [Required]
        public string FirstName { get; set;}
        public string MiddleName { get; set;}
        [Required]
        public string LastName { get; set;}
        public string Suffix { get; set;}
        public string EmailAddress { get; set;}
        [Required]
        public int EmailPromotion { get; set;}
        public string Phone { get; set;}
        [Required]
        public string PasswordHash { get; set;}
        [Required]
        public string PasswordSalt { get; set;}
        public string AdditionalContactInfo { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("VendorAddress")]
    public partial class VendorAddress : IHasId<int>    {
        [Alias("VendorID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int AddressID { get; set;}
        [Required]
        public int AddressTypeID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("VendorContact")]
    public partial class VendorContact : IHasId<int>    {
        [Alias("VendorID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ContactID { get; set;}
        [Required]
        public int ContactTypeID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("PurchaseOrderHeader")]
    public partial class PurchaseOrderHeader : IHasId<int>    {
        [Alias("PurchaseOrderID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public byte RevisionNumber { get; set;}
        [Required]
        public byte Status { get; set;}
        [Required]
        public int EmployeeID { get; set;}
        [Required]
        public int VendorID { get; set;}
        [Required]
        public int ShipMethodID { get; set;}
        [Required]
        public DateTime OrderDate { get; set;}
        public DateTime? ShipDate { get; set;}
        [Required]
        public decimal SubTotal { get; set;}
        [Required]
        public decimal TaxAmt { get; set;}
        [Required]
        public decimal Freight { get; set;}
        [Required]
        public decimal TotalDue { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ContactCreditCard")]
    public partial class ContactCreditCard : IHasId<int>    {
        [Alias("ContactID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int CreditCardID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("WorkOrder")]
    public partial class WorkOrder : IHasId<int>    {
        [Alias("WorkOrderID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public int OrderQty { get; set;}
        [Required]
        public int StockedQty { get; set;}
        [Required]
        public short ScrappedQty { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public DateTime DueDate { get; set;}
        public short? ScrapReasonID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ContactType")]
    public partial class ContactType : IHasId<int>    {
        [Alias("ContactTypeID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("CountryRegionCurrency")]
    public partial class CountryRegionCurrency : IHasId<string>    {
        [Alias("CountryRegionCode")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string CurrencyCode { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("WorkOrderRouting")]
    public partial class WorkOrderRouting : IHasId<int>    {
        [Alias("WorkOrderID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public short OperationSequence { get; set;}
        [Required]
        public short LocationID { get; set;}
        [Required]
        public DateTime ScheduledStartDate { get; set;}
        [Required]
        public DateTime ScheduledEndDate { get; set;}
        public DateTime? ActualStartDate { get; set;}
        public DateTime? ActualEndDate { get; set;}
        public decimal? ActualResourceHrs { get; set;}
        [Required]
        public decimal PlannedCost { get; set;}
        public decimal? ActualCost { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("CountryRegion")]
    public partial class CountryRegion : IHasId<string>    {
        [Alias("CountryRegionCode")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("CreditCard")]
    public partial class CreditCard : IHasId<int>    {
        [Alias("CreditCardID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string CardType { get; set;}
        [Required]
        public string CardNumber { get; set;}
        [Required]
        public byte ExpMonth { get; set;}
        [Required]
        public short ExpYear { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Culture")]
    public partial class Culture : IHasId<string>    {
        [Alias("CultureID")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Currency")]
    public partial class Currency : IHasId<string>    {
        [Alias("CurrencyCode")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesOrderDetail")]
    public partial class SalesOrderDetail : IHasId<int>    {
        [Alias("SalesOrderID")]
        [Required]
        public int Id { get; set;}
        [AutoIncrement]
        public int SalesOrderDetailID { get; set;}
        public string CarrierTrackingNumber { get; set;}
        [Required]
        public short OrderQty { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public int SpecialOfferID { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public decimal UnitPriceDiscount { get; set;}
        [Required]
        public decimal LineTotal { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("CurrencyRate")]
    public partial class CurrencyRate : IHasId<int>    {
        [Alias("CurrencyRateID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime CurrencyRateDate { get; set;}
        [Required]
        public string FromCurrencyCode { get; set;}
        [Required]
        public string ToCurrencyCode { get; set;}
        [Required]
        public decimal AverageRate { get; set;}
        [Required]
        public decimal EndOfDayRate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Customer")]
    public partial class Customer : IHasId<int>    {
        [Alias("CustomerID")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? TerritoryID { get; set;}
        [Required]
        public string AccountNumber { get; set;}
        [Required]
        public string CustomerType { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesOrderHeader")]
    public partial class SalesOrderHeader : IHasId<int>    {
        [Alias("SalesOrderID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public byte RevisionNumber { get; set;}
        [Required]
        public DateTime OrderDate { get; set;}
        [Required]
        public DateTime DueDate { get; set;}
        public DateTime? ShipDate { get; set;}
        [Required]
        public byte Status { get; set;}
        [Required]
        public bool OnlineOrderFlag { get; set;}
        [Required]
        public string SalesOrderNumber { get; set;}
        public string PurchaseOrderNumber { get; set;}
        public string AccountNumber { get; set;}
        [Required]
        public int CustomerID { get; set;}
        [Required]
        public int ContactID { get; set;}
        public int? SalesPersonID { get; set;}
        public int? TerritoryID { get; set;}
        [Required]
        public int BillToAddressID { get; set;}
        [Required]
        public int ShipToAddressID { get; set;}
        [Required]
        public int ShipMethodID { get; set;}
        public int? CreditCardID { get; set;}
        public string CreditCardApprovalCode { get; set;}
        public int? CurrencyRateID { get; set;}
        [Required]
        public decimal SubTotal { get; set;}
        [Required]
        public decimal TaxAmt { get; set;}
        [Required]
        public decimal Freight { get; set;}
        [Required]
        public decimal TotalDue { get; set;}
        public string Comment { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("CustomerAddress")]
    public partial class CustomerAddress : IHasId<int>    {
        [Alias("CustomerID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int AddressID { get; set;}
        [Required]
        public int AddressTypeID { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Department")]
    public partial class Department : IHasId<short>    {
        [Alias("DepartmentID")]
        [AutoIncrement]
        public short Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public string GroupName { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Document")]
    public partial class Document : IHasId<int>    {
        [Alias("DocumentID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Title { get; set;}
        [Required]
        public string FileName { get; set;}
        [Required]
        public string FileExtension { get; set;}
        [Required]
        public string Revision { get; set;}
        [Required]
        public int ChangeNumber { get; set;}
        [Required]
        public byte Status { get; set;}
        public string DocumentSummary { get; set;}
        //TODO: Handle byte format
//        [Alias("Document")]
//        public byte[]? _Document { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Employee")]
    public partial class Employee : IHasId<int>    {
        [Alias("EmployeeID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string NationalIDNumber { get; set;}
        [Required]
        public int ContactID { get; set;}
        [Required]
        public string LoginID { get; set;}
        public int? ManagerID { get; set;}
        [Required]
        public string Title { get; set;}
        [Required]
        public DateTime BirthDate { get; set;}
        [Required]
        public string MaritalStatus { get; set;}
        [Required]
        public string Gender { get; set;}
        [Required]
        public DateTime HireDate { get; set;}
        [Required]
        public bool SalariedFlag { get; set;}
        [Required]
        public short VacationHours { get; set;}
        [Required]
        public short SickLeaveHours { get; set;}
        [Required]
        public bool CurrentFlag { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesOrderHeaderSalesReason")]
    public partial class SalesOrderHeaderSalesReason : IHasId<int>    {
        [Alias("SalesOrderID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int SalesReasonID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesPerson")]
    public partial class SalesPerson : IHasId<int>    {
        [Alias("SalesPersonID")]
        [Required]
        public int Id { get; set;}
        public int? TerritoryID { get; set;}
        public decimal? SalesQuota { get; set;}
        [Required]
        public decimal Bonus { get; set;}
        [Required]
        public decimal CommissionPct { get; set;}
        [Required]
        public decimal SalesYTD { get; set;}
        [Required]
        public decimal SalesLastYear { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("EmployeeAddress")]
    public partial class EmployeeAddress : IHasId<int>    {
        [Alias("EmployeeID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int AddressID { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("EmployeeDepartmentHistory")]
    public partial class EmployeeDepartmentHistory : IHasId<int>    {
        [Alias("EmployeeID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public short DepartmentID { get; set;}
        [Required]
        public byte ShiftID { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("EmployeePayHistory")]
    public partial class EmployeePayHistory : IHasId<int>    {
        [Alias("EmployeeID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTime RateChangeDate { get; set;}
        [Required]
        public decimal Rate { get; set;}
        [Required]
        public byte PayFrequency { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesPersonQuotaHistory")]
    public partial class SalesPersonQuotaHistory : IHasId<int>    {
        [Alias("SalesPersonID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTime QuotaDate { get; set;}
        [Required]
        public decimal SalesQuota { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Illustration")]
    public partial class Illustration : IHasId<int>    {
        [Alias("IllustrationID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Diagram { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesReason")]
    public partial class SalesReason : IHasId<int>    {
        [Alias("SalesReasonID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public string ReasonType { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Individual")]
    public partial class Individual : IHasId<int>    {
        [Alias("CustomerID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ContactID { get; set;}
        public string Demographics { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesTaxRate")]
    public partial class SalesTaxRate : IHasId<int>    {
        [Alias("SalesTaxRateID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int StateProvinceID { get; set;}
        [Required]
        public byte TaxType { get; set;}
        [Required]
        public decimal TaxRate { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("JobCandidate")]
    public partial class JobCandidate : IHasId<int>    {
        [Alias("JobCandidateID")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? EmployeeID { get; set;}
        public string Resume { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Location")]
    public partial class Location : IHasId<short>    {
        [Alias("LocationID")]
        [AutoIncrement]
        public short Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public decimal CostRate { get; set;}
        [Required]
        public decimal Availability { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesTerritory")]
    public partial class SalesTerritory : IHasId<int>    {
        [Alias("TerritoryID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public string CountryRegionCode { get; set;}
        [Required]
        public string Group { get; set;}
        [Required]
        public decimal SalesYTD { get; set;}
        [Required]
        public decimal SalesLastYear { get; set;}
        [Required]
        public decimal CostYTD { get; set;}
        [Required]
        public decimal CostLastYear { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Product")]
    public partial class Product : IHasId<int>    {
        [Alias("ProductID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public string ProductNumber { get; set;}
        [Required]
        public bool MakeFlag { get; set;}
        [Required]
        public bool FinishedGoodsFlag { get; set;}
        public string Color { get; set;}
        [Required]
        public short SafetyStockLevel { get; set;}
        [Required]
        public short ReorderPoint { get; set;}
        [Required]
        public decimal StandardCost { get; set;}
        [Required]
        public decimal ListPrice { get; set;}
        public string Size { get; set;}
        public string SizeUnitMeasureCode { get; set;}
        public string WeightUnitMeasureCode { get; set;}
        public decimal? Weight { get; set;}
        [Required]
        public int DaysToManufacture { get; set;}
        public string ProductLine { get; set;}
        public string Class { get; set;}
        public string Style { get; set;}
        public int? ProductSubcategoryID { get; set;}
        public int? ProductModelID { get; set;}
        [Required]
        public DateTime SellStartDate { get; set;}
        public DateTime? SellEndDate { get; set;}
        public DateTime? DiscontinuedDate { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SalesTerritoryHistory")]
    public partial class SalesTerritoryHistory : IHasId<int>    {
        [Alias("SalesPersonID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int TerritoryID { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ScrapReason")]
    public partial class ScrapReason : IHasId<short>    {
        [Alias("ScrapReasonID")]
        [AutoIncrement]
        public short Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("Shift")]
    public partial class Shift : IHasId<byte>    {
        [Alias("ShiftID")]
        [AutoIncrement]
        public byte Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public DateTime StartTime { get; set;}
        [Required]
        public DateTime EndTime { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductCategory")]
    public partial class ProductCategory : IHasId<int>    {
        [Alias("ProductCategoryID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ShipMethod")]
    public partial class ShipMethod : IHasId<int>    {
        [Alias("ShipMethodID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public decimal ShipBase { get; set;}
        [Required]
        public decimal ShipRate { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductCostHistory")]
    public partial class ProductCostHistory : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public decimal StandardCost { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductDescription")]
    public partial class ProductDescription : IHasId<int>    {
        [Alias("ProductDescriptionID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Description { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ShoppingCartItem")]
    public partial class ShoppingCartItem : IHasId<int>    {
        [Alias("ShoppingCartItemID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string ShoppingCartID { get; set;}
        [Required]
        public int Quantity { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public DateTime DateCreated { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductDocument")]
    public partial class ProductDocument : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int DocumentID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductInventory")]
    public partial class ProductInventory : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public short LocationID { get; set;}
        [Required]
        public string Shelf { get; set;}
        [Required]
        public byte Bin { get; set;}
        [Required]
        public short Quantity { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SpecialOffer")]
    public partial class SpecialOffer : IHasId<int>    {
        [Alias("SpecialOfferID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Description { get; set;}
        [Required]
        public decimal DiscountPct { get; set;}
        [Required]
        public string Type { get; set;}
        [Required]
        public string Category { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        [Required]
        public DateTime EndDate { get; set;}
        [Required]
        public int MinQty { get; set;}
        public int? MaxQty { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductListPriceHistory")]
    public partial class ProductListPriceHistory : IHasId<int>    {
        [Alias("ProductID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public DateTime StartDate { get; set;}
        public DateTime? EndDate { get; set;}
        [Required]
        public decimal ListPrice { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("SpecialOfferProduct")]
    public partial class SpecialOfferProduct : IHasId<int>    {
        [Alias("SpecialOfferID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ProductID { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductModel")]
    public partial class ProductModel : IHasId<int>    {
        [Alias("ProductModelID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string Name { get; set;}
        public string CatalogDescription { get; set;}
        public string Instructions { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("StateProvince")]
    public partial class StateProvince : IHasId<int>    {
        [Alias("StateProvinceID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string StateProvinceCode { get; set;}
        [Required]
        public string CountryRegionCode { get; set;}
        [Required]
        public bool IsOnlyStateProvinceFlag { get; set;}
        [Required]
        public string Name { get; set;}
        [Required]
        public int TerritoryID { get; set;}
        [Required]
        public Guid rowguid { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ProductModelIllustration")]
    public partial class ProductModelIllustration : IHasId<int>    {
        [Alias("ProductModelID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int IllustrationID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("DatabaseLog")]
    public partial class DatabaseLog : IHasId<int>    {
        [Alias("DatabaseLogID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime PostTime { get; set;}
        [Required]
        public string DatabaseUser { get; set;}
        [Required]
        public string Event { get; set;}
        public string Schema { get; set;}
        public string Object { get; set;}
        [Required]
        public string TSQL { get; set;}
        [Required]
        public string XmlEvent { get; set;}
    }
    
	[Alias("ProductModelProductDescriptionCulture")]
    public partial class ProductModelProductDescriptionCulture : IHasId<int>    {
        [Alias("ProductModelID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public int ProductDescriptionID { get; set;}
        [Required]
        public string CultureID { get; set;}
        [Required]
        public DateTime ModifiedDate { get; set;}
    }
    
	[Alias("ErrorLog")]
    public partial class ErrorLog : IHasId<int>    {
        [Alias("ErrorLogID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public DateTime ErrorTime { get; set;}
        [Required]
        public string UserName { get; set;}
        [Required]
        public int ErrorNumber { get; set;}
        public int? ErrorSeverity { get; set;}
        public int? ErrorState { get; set;}
        public string ErrorProcedure { get; set;}
        public int? ErrorLine { get; set;}
        [Required]
        public string ErrorMessage { get; set;}
    }
	
}

